<?php

/**
 * Implements hook_menu_alter()
 *
 * @param array $items
 *   Format: $[$files_dir . '/styles/%image_style'] = $router_item
 */
function imagestyle404_menu_alter(array &$items) {

  /** @var DrupalLocalStreamWrapper $public_stream_wrapper */
  $public_stream_wrapper = file_stream_wrapper_get_instance_by_scheme('public');
  $public_files_dir = $public_stream_wrapper->getDirectoryPath();
  /* @see image_style_load() */
  $original_router_path = $public_files_dir . '/styles/%image_style';

  if (!isset($items[$original_router_path])) {
    return;
  }

  $item = $items[$original_router_path];

  if ('image_style_deliver' !== $item['page callback']) {
    return;
  }

  /* @see _imagestyle404_image_style_deliver() */
  $item['page callback'] = '_imagestyle404_image_style_deliver';

  $item[$original_router_path] = $item;
}

/**
 * Page callback. Replaces image_style_deliver().
 *
 * @param array $style
 *   The image style definition array.
 * @param string $scheme
 *   The file scheme, for example 'public' for public files.
 *
 * @return mixed
 * @see \image_style_deliver()
 * @see \drupal_deliver_page()
 */
function _imagestyle404_image_style_deliver(array $style, $scheme = NULL) {

  if (NULL === $scheme) {
    return _imagestyle404_deliver_failure(
        '404 Not Found',
        'Too few url parts for image style generation: Scheme missing.');
  }

  $args = func_get_args();

  $result = call_user_func_array('image_style_deliver', $args);

  if (MENU_ACCESS_DENIED === $result) {
    return _imagestyle404_deliver_failure('403 Forbidden');
  }

  if (MENU_NOT_FOUND === $result) {
    return _imagestyle404_deliver_failure('404 Not Found');
  }

  // This should be unreachable code, because image_style_deliver() never
  // returns anything else.
  return $result;
}

/**
 * @param string $status
 * @param string|null $message
 *   Custom message that will be added in a custom header.
 *
 * @return null
 *   This never happens, instead it always calls drupal_exit().
 *   The return statement is a lazy way to make the IDE happy.
 */
function _imagestyle404_deliver_failure($status, $message = NULL) {
  drupal_add_http_header('Status', $status);
  if (NULL !== $message) {
    // Custom http header: See https://stackoverflow.com/a/19640336/246724
    drupal_add_http_header('X-Drupal-imagestyle404-Message', $message);
  }
  // See https://stackoverflow.com/a/3203394/246724
  drupal_add_http_header('Content-type', 'image/png');
  echo base64_decode('R0lGODlhAQABAJAAAP8AAAAAACH5BAUQAAAALAAAAAABAAEAAAICBAEAOw==');
  drupal_exit();
  // Tell the IDE that the function ends here.
  return NULL;
}
